# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'active_fire_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ActiveFireDialogBase(object):
    def setupUi(self, ActiveFireDialogBase):
        ActiveFireDialogBase.setObjectName("ActiveFireDialogBase")
        ActiveFireDialogBase.resize(330, 461)
        self.label_5 = QtWidgets.QLabel(ActiveFireDialogBase)
        self.label_5.setGeometry(QtCore.QRect(20, 430, 331, 16))
        self.label_5.setObjectName("label_5")
        self.widget = QtWidgets.QWidget(ActiveFireDialogBase)
        self.widget.setGeometry(QtCore.QRect(20, 30, 277, 251))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.widget1 = QtWidgets.QWidget(ActiveFireDialogBase)
        self.widget1.setGeometry(QtCore.QRect(20, 280, 277, 131))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_4.addWidget(self.pushButton_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)

        self.retranslateUi(ActiveFireDialogBase)
        self.pushButton_3.clicked.connect(ActiveFireDialogBase.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ActiveFireDialogBase)

    def retranslateUi(self, ActiveFireDialogBase):
        _translate = QtCore.QCoreApplication.translate
        ActiveFireDialogBase.setWindowTitle(_translate("ActiveFireDialogBase", "Active Fire"))
        self.label_5.setText(_translate("ActiveFireDialogBase", "© Pawel Dzierzynski"))
        self.label_2.setText(_translate("ActiveFireDialogBase", "Number of firepixels detected by MODIS 1KM:"))
        self.pushButton.setText(_translate("ActiveFireDialogBase", "MODIS 1KM "))
        self.label_3.setText(_translate("ActiveFireDialogBase", "Number of firepixels detected by VIIRS 375M/S-NPP:"))
        self.pushButton_2.setText(_translate("ActiveFireDialogBase", "VIIRS 375M/S-NPP"))
        self.label.setText(_translate("ActiveFireDialogBase", "Number of firepixels detected by VIIRS 375M/NOAA-20:"))
        self.pushButton_4.setText(_translate("ActiveFireDialogBase", "VIIRS 375M/NOAA-20"))
        self.label_4.setText(_translate("ActiveFireDialogBase", "Number of firepixels detected by VIIRS 375m / NOAA-21:"))
        self.pushButton_5.setText(_translate("ActiveFireDialogBase", "VIIRS 375m / NOAA-21"))
        self.pushButton_3.setText(_translate("ActiveFireDialogBase", "Exit"))
